name: Linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install FreeType2
        run: | 
            sudo apt-get update
            sudo apt-get install -y \
                libfreetype-dev \
                libharfbuzz-dev \
                libfontconfig1-dev \
                build-essential \
                pkg-config \
                build-essential
      - name: update font cache
        run: |
             sudo fc-cache -f -v

             # verification check
             fc-list : family | grep -i "Noto Serif"
        
      - name: Verify Mappings and Compile
        run: | 
             # diagnostics: ensure 
             pkg-config --cflags --libs freetype2 harfbuzz
      - name: Install Dependencies
        run: zef install --/test --test-depends --deps-only .
      - name: Install App::Prove6
        run: zef install --/test App::Prove6
      - name: Run Tests
        run: prove6 -I. t
