name: Linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Check repository
        run: |
             test -f META6.json
             echo "META6.json found"
